#!/usr/bin/env bash
output=$(php php-cs-fixer.phar fix --no-interaction --dry-run )
echo ""
length=$(echo "$output" | wc -l)
if [[ $length -gt 2 ]]; then
    while read -r line
    do
        echo -e "\e[37;41m$line\e[00m"
    done <<< "$output"
    false
else
    echo -e "\e[30;42mCoding standards are OK\e[0m"
fi
